# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-traefik-bouncer-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    #ENC[AES256_GCM,data:0TLiCgAJB4Qx8AA8rsxpbIyo0wFXLto/0jSIE4evKQ69MiD8DUpV/5dAkBEvkzhvN4gRpCJ0IShhIsiDU6EcJzaCHEpCk8I7KW8J4BWF,iv:KAyruHlx7DS3rVbu8oNlT/wXv2AHykU8ddspYEuTFMY=,tag:akCrtXDXFdpsl5pox8V5hQ==,type:comment]
    #ENC[AES256_GCM,data:fldJ5BAxJ7qDsU19kAAuPkjI+4zzFCjCGMfPet52euIw8mmMZ/OtZyezJmSO4Iq4mMueyfRYk8XuV0oy2maBriRtEZyTnPltRnOMOtGN0zhuhKmaMg==,iv:vbQKjfP0Qa1v8C288IxJEoPiosQmfrblJ/uYiqWlZCk=,tag:epKitA5oPLFbttPGJyCmYQ==,type:comment]
    crowdsec_bouncer_api_key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSFVvaENZYVVPUGJoZ3JF
            eXVEYmFlQ0lFQXBVUFJmVFh4YXpwTVVxZEJ3Cm11cEdZcDJZWUhOVjZCMzNPOSt6
            MktpcHdpRXN4NTArdmY1Z2liSEM1cmcKLS0tIGtOdFJyTGIwWFdGZE16eTlkQXdo
            MWFMWmlFV0dVa0k3TWswSmZ6TCtqQUkKKhXhwNnI8BWI6fJ/jLztdU7rEAGmZiCq
            464YP1whR+APsL2ID6F/EOGLimTGpLsNVDZSsTTf3qNqw90vuXsikA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:12Z"
    mac: ENC[AES256_GCM,data:bdc8/9LhPJAge6/8FYLi2KFN45HTNYN4WNF7q2HNO7Q08hNZyJtnThlQuhwpH4n5kfPJmUbhK6+YW7vSVsBsN65h8uB+myal4VzuhTC2m2YezJr7Y4hxQBcfR1mYlV6nANNTp+rKqlWaSgVcFIJzHO8Qq6QraEFZkasa9E1f/9U=,iv:IvqprU0KoNGNH4YUB97kvsIRdfQOKkx/7QQ4KNkMQls=,tag:R9UkcfDL2GfnQ7Qw60Fgog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
