# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:kpXuBVM=,iv:vU9yzkFPBVCEll9TRgUV3YhLfTPyaFcEvZh0KSJpNew=,tag:skIBVxEsekGlQ4BQ1ocfow==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:bLFm9oZvLWUL+ZlmFUS96A+I53DDo1RxRB7tE9d2r1lr3zUAva0X8TDCSQSJEg==,iv:mBS+XM4LloDkvQzpDhNB94uSqOiVKxh5v4FJ3ngOoK4=,tag:L9i9Cya3zFA3TcQGnBSibw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnanY0cHA3cVJ1ZEZrRmJM
            NXhLYVdTeG9RYTQ1MFBUcDdFQldlY0pERUhrCnFZSUZLRVA1M1JIU3VjZE84WS9z
            TDdGYnc0a1pzdU1JeDB0Wjd1WXJ0MTQKLS0tIHE1SW84SXp2dDdjQlM5d3dnTTdo
            MUExYnVvNEV2ZVJnT0xuakx0U1dQT0EKUKcu+Fzv612udavl/BXTqzHdlJPakfvU
            m8rgGZ2V0rnQdM3WVOkwjGcPEqG8bxi/Lj3pugokQGl3vhfz3S3PUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:55:59Z"
    mac: ENC[AES256_GCM,data:Ul1CV2JehfzS/kESX5bKf5KNFfnKOJObOmbjmAtjbWGqhKlA84SMMvXNN8GvFBIte0t7pQEVd95Yae0IRRFeq21K2/zDUtIW0rY47UouJ0NHwa9ra4GaHfkqc9/VsBubsgne+zyzm4nLm8vay3ndUkg9rFjygp9F5Rh6WZYF5S0=,iv:A04mxLhLUBfcbIuKDl6ZCZ5Pl8u8GFJZ/k6Tx1aj8CI=,tag:6RlU7WVpxl/6ecZydzNMfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
