# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:zT4KJBw=,iv:K+8sG7A0411yhL+8b/EdEAiVq/uVOjNx0R55h1/kYoc=,tag:2zNqZCToQusU3k1ywjygdQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:3dj/S1xeaRPpMsCqazGhQJyfVQdIVuDj6QLTRKdSnqwmIjBiD3E6JjjiCbddow==,iv:wyYwzcOL/N8ke/o9HaUkuHhf9wv4QiZ5bvpeQQTLRzU=,tag:FmkHL+D3xdlcUk+Rjrwg5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eEpWaGVNMk1aeUJtRkpw
            N3I1ODJFMHYxRnVyR0lDbHJmWVoxRGljQXdZCkVmdW9ndkpxdXpDcWFDSlBhc3p1
            U0UvcWE1d29DVXNSZGRkNWRqSmw1U2cKLS0tIDkxTmJTbmRheHJPeDlGMnVpWUdL
            T1FIS3NEbk0vcUlUNVR2VEZwZ0NMRVkKRTVkNnH3gE9ytzefgIb3CeNQcDJ4CFcK
            Unox3da7Gw9713yji+fqA6UptoW+XW5f+HzAXwZugiWzxPNpcHqlsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:FR3mfJ023CjJAgO1nwbxTIaDb3gfNCVbxT8dG8wxLvSqm6Ev0T+BAI9jyvpC1/Tnv1sysjJx/MBEV2hTQ/CiB74H0+oqJ7IW8BF4M8c28fbvUMlXAUqCgLqYvcRBIwEQekXWrEzfUPiZWTpX1GR0NPxwNgZDxfEaeA3mdgMB2pg=,iv:tf1BEaICeV00kCkTDI10fh8PlVuoS+pryfObIRivy2Q=,tag:F5+ymAxhFdcEv+xVagQPmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
