apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    namespace: dev
stringData:
    postgresql-password: 78v67dv7f5765v75v78sr5vgr5v
    postgresql-replication-password: xx9s8c7d987c89dw7c8979c87e98rmc7r7
