---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-default-home-assistant-db
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/home-assistant/db
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-gitops-k3s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: home-assistant-db
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-default-home-assistant
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-default-home-assistant-db
  path: ./kubernetes/apps/default/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-gitops-k3s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: home-assistant
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
