---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-longhorn
  namespace: flux-system
spec:
  path: ./kubernetes/apps/longhorn/longhorn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-gitops-k3s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
