---
creation_rules:
  - encrypted_regex: "^(data|stringData)$"
    age: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
  - path_regex: kubernetes/.*\.sops\.toml
    key_groups:
      - age:
          - age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
