---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2023.3.6@sha256:5f61d3fe876824d980c17f9a085a46b97ee838421abe50b43e4a8386292a35ad
    env:
      TZ: "${TIMEZONE}"
      HASS_IP: 10.2.1.100
    envFrom:
      - secretRef:
          name: home-assistant-secrets
    service:
      main:
        # type: LoadBalancer
        # loadBalancerIP: 10.2.1.100
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.11.0
        env:
          TZ: "${TIMEZONE}"
          EMAIL: fiqrimasngot@akudanlasagna.online
          GIT_AUTHOR_NAME: Fiqri Masngot
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: false
        volumeMounts:
          - name: config
            mountPath: /config
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    resources:
      requests:
        cpu: 48m
        memory: 443M
      limits:
        memory: 709M
