apiVersion: v1
kind: Secret
metadata:
    name: mealie-restic-secret
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9x1FDh6WOucM06BXygHs5g9x4sSC7G3crFzDwJSBSVePs64W5W39VtTwOGp4hisaexvV50xniQnv44TsGzOtOfiPo6XGQrc7Jectb1W8cOQ=,iv:3yWf4GaHj8latCOvLUrpmRI4aNOJsuQrsJg1KT5iBrk=,tag:MNQbtjPppHqeWAAfIauC5A==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:pj/QqqihgFXCCcRIbZLOmSHOt/ImVBSp3g==,iv:omRBfZLPvdM7utGiEy25Hwb0rMMq4G+yAzjn64JUYTQ=,tag:PiiDC6txcDMWqQqBMMJeaQ==,type:str]
    #ENC[AES256_GCM,data:9PEUt3Z5qrIeWkoIr78ql/S4U/w2qd2E98qLZ9fy,iv:gXC7+W0GVqoRoj41RifkzMvlQCUNwJoH19OJsvALR8U=,tag:LaUm3sVo4DQ3S29j7GLTgQ==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:5a0n5zpM8RRGbEDJ63bGDRxoj3QFQBX5hk0ZnVQeAAoDQOuIyqWpsZjvIkhDzA==,iv:1EpT6e2vIBQEKLCCIznQf72f+6IXHG9oRHXM0orduUc=,tag:7RyeQ2c+nL776xoffAIT/w==,type:str]
    #ENC[AES256_GCM,data:jjqP5XeSBFRUuTuMLXjxiCt0Y9qhKa6I/iPPYDDWFFPWrZH08DX/Zwo=,iv:PmFbfoSJrr/0tGrlCjmzUrQXU7hVfT/tta+aq5P4JDI=,tag:8lUGMWB6fsvdrqVzRQ1HxQ==,type:comment]
    #ENC[AES256_GCM,data:KKvq2KYgxkxG6sgqMnfL5T1UENkbD5HAaeioswtJ0PN5/w5lTHAOQ2f2aAEz/CiltTHObYa2CTOQMoFqBky+IxIrzRnhWw==,iv:4WR983+NsxOfNXwmileOmBTpJyIewikrIqymDP70NqA=,tag:T279fFckxtPHKwQ5vpS64g==,type:comment]
    AWS_ACCESS_KEY_ID: null
    AWS_SECRET_ACCESS_KEY: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZ1R5aUgyTDJpTkJaNC9N
            c2dWQWE3V21MU3haUnB2bUwyZWhBK3p6ZTJNCjFWL2tueE1lTW1kblJCc1JYR0Ev
            aCtWSFJ3OHZDRkFLdmtITDEzQmZsTjQKLS0tIEtjVnIvYVNwQ1JYWnIvL3YyKzRI
            azZTTXVUUjcwOUpGU3YyNStvRFJhSEUKxPbu3LDmq4d9Q3lZhde47Xvt13GUq2Sf
            gHD0/BzA7eR7chB4Tv/UswKfyctoM3wf7R+DC5y5NmThwG2Hs1NAzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:lwEmx1VaxlpBdRK+B3PWImOAt/CAyl4sceIUKHIDcJp2NT/gX2Xq9vBdhXZhaLOiU1GDgiPl/P44nNQEwH3/GZnVxFUuP1Bt/gbE+2O9kUzhLGkbAR7cAT6f0r88XeX7SFL7dOpSHOL1i3lGi0wvJ0Klo7FMxA60j93DLOjRIw4=,iv:Oyj/cvlPDOfxWrhgmQj/BKLVXr6YytKHIJ3VaqVE/ew=,tag:29amMMPpwhvMNlV5riXHpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
