---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrutiny-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
