apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-connection
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    values.yaml: |
        # Define connection to postgres database server
        postgres:
          # postgres hostname
          host: "postgres-postgresql-hl.default.svc.cluster.local"
          # postgres admin user and password
          user: "postgres"
          password: "78v67dv7f5765v75v78sr5vgr5v"
          # additional connection args to pg driver
          uri_args: ""
          # postgres cloud provider, could be AWS, Azure, GCP or empty (default)
          cloud_provider: ""
          # default database to use
          default_database: "postgres"
