apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-connection
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:9hzXy4XnMM3Kx+SVLcOBmhRJ3cuobD6Q4ozuR5Zv5Zwik7lBE3Cv61A1TlGLP1LghYQUvqahXRkGPnfmrmHRHo/04Lr+TAThA4HQPtd3fs1kMI3SU2g6prE/ekgxFXk7jaG5AIs01fPHZVkDrN9Qc/fdi+pkYPNPBEKnkA4iLI4E/Ar553iRFcGy4D/EojkFlBpRZ+I8QC0HkGHtOevM4YgI2/cAH3I9EhdWHoUN55KFhZnZUP7zaoV5qp35YHonR7AapTSGEx+tQwD1HzGeWUTDrnc8kvfmW2xM9kyRmrOaQPl9U1h+w6iNEpBlESSVkIqPJBMNGQEdIN7OOB3rl6kbcQCqA3CNtud+Q3kSY1NC7gq6l2kPU/GEdQG54SO/wfNPrM42OrQdaRpjbpWuDpu/gpbMHbA3q8UCT2V7NuqSwrozgZnlxqGzWYLewcLZfP90CsQObI0/1IFndtrhJh+drKMR6mRGjcG5of0NwSvqSj3NrgqbRZgmROsf34aob5yP0M+IkZTeb8V2MgiAw28Bq4xYu0XGmi4E,iv:0h93Zb5ru6l9adfzu5tgASTRmka9G+bDafL1xLqQWvY=,tag:3NyVb/VOgogq7dGIB6xXfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UFlydi95MUFFSnhzMktv
            NGN2K1VQT2p4T2dRUEVneWVpczlJaS9qYlRFCjQ4TlA0cG9kbEc1YnA0UFVXSVJL
            SnQyTitqTmFIUzJtcUdVZDk0Y0NyNzQKLS0tIGJNTytmSmduZFJwakVXUzdlQVE4
            Q1oySnRxUHRDcktBM215OXZpU1JwM0UKDdq44ElgPj2BVPsbLQk5iFLANSXlvUMD
            OYyeSCWf3c/4+YHBtwlUFUSfjBVvBTVlrbQuYb8WIDw570AtjvrfgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:iU7oEwKZG9OAVWvysgDa/gkQG5GCA5YqmuPNKLUyLjGS3I1jMZk3xhwV2bFzEe0KiN6PRsTgzdZ85/3gbNYb1EVcg+U3Cr8+9GosLt/isq0XTWWDjwbFLgxMZAVL2t6AMbUHHGshMgLonrr/IgNhLpLbYlRd7N/XBorF53sqmrI=,iv:hDlmt3reUFCRdil/SAOm2zQeNq1Tom24gbalVdPFu3Q=,tag:Dm1yyesXbtI4DL45zoAspA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
