apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-connection
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:il5yBSJwmTaNwQTnJF07OAgYlOS1vWi1T112ZCzPldNVcrRoYdb/PdsBFb54miBjRhQo4CwNvXfG9g0BJE4ZlVJTvumLW0Gej9+7q+VLw9CJ3ARBBxf9IKIzatpEXugwqgobPIbUw9ov/XS8guN9p9GStlHzKEeaSnrXxxGnCMtE56mBy2xGZ/Jrj0FvZ94fdsipC2l4JhkzTOGghPkHgHlNGYQm+LqyRbyUZpymkazDXqiPGYjSYbSaDRQ0d7iYmp1mAN2tGNaGt2FmAFg/Za/KrXxa33hNV4nJ0a3+FMhNkhwGtuH7YP+oD43SQX4A4ZZMd+LFie6TOCAjkVkHXMXmQXpwPRqEc9XLmj6eomNhOoSyoBtdCDhKGC2niGDQ+PKHgCKDoLJs300SsBsrhQS6x2MuFTzvXruT3vnyAbQXELwKEUTDUdwF893+QYh6bb7oUqL9PNCj2yGeNDG+9n4RVU9DvN02jnVYkTCu/b9kttJ6oSehQwrM0FmN6rIU7blVABeFfvr6SslgQbPylApC1JGcy/brQ1jIhuX7y9BdFY6swlf1hsVOGhFb18nGfGlPCOMJX01X+Cbj6VpZHw==,iv:niQ6arSW72hpss0qDZ7FJ7Gd8ptXq2tFXAmgyypiwVs=,tag:aiLvS2pRuQF9D6p3avXfcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UFlydi95MUFFSnhzMktv
            NGN2K1VQT2p4T2dRUEVneWVpczlJaS9qYlRFCjQ4TlA0cG9kbEc1YnA0UFVXSVJL
            SnQyTitqTmFIUzJtcUdVZDk0Y0NyNzQKLS0tIGJNTytmSmduZFJwakVXUzdlQVE4
            Q1oySnRxUHRDcktBM215OXZpU1JwM0UKDdq44ElgPj2BVPsbLQk5iFLANSXlvUMD
            OYyeSCWf3c/4+YHBtwlUFUSfjBVvBTVlrbQuYb8WIDw570AtjvrfgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T08:09:29Z"
    mac: ENC[AES256_GCM,data:Lgfg2dhkoF8HaAEozHpOkGSGAULNipI/H/6FdxFxdbx6ZFGlh2Yeq4g0cu9+CGWualnX+om8PaYsQiXSjl54jTixdIOh1ccdI3FAjtfKln1hqRnr0nD7SeXZBF79I+IX2vcNUdXam3gmLqEgoPM5AAJJmiO/kmDkiI3fBEhJDjQ=,iv:QK5++tS/SJ5vH9fzkv7dM2cgr0q+VuhO9zlrVZqWgrc=,tag:AUnsxbG3nE11ikznq8C7GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
