apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-connection
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:UVD4yZHU76CoW4YCEYATdRzTCMQtPJEBcYqHshv14qTfg1RzgO0EvloCqTS2tdLUFGQ6h1/mGbGBCl5KBgxVbPEsbQBSMKKqQbMl3+mPV/nMlxytf61Tt9PthBi2UlOSAjE+DuOKOnF2NGBZmA2kzpdEhhWb35wSLdZON5DNNuLlC3y+7sYyEFwp76NsHPAcbqIU90LXNz01MjsTb50HJjrU2FY/NTj09uEaaU8gJJnfNqF1mlJrd6yv8Nxm6HffrsJbPW/jh4ED9iSNLjcpSMzfwnNEYCvt2BoRG3RnIHt8MrE5LYxV6YOO9IFqFvMLKMkiOADyH/BbQa0gpH9c6aaCT3ljRn2OpBigDWI2XHbmlJLqtvbvFLIIcwXaWW0u799Gjv27QByyBxeiK6HxBXvrQDawzWvn7oLjFyvP0y28sZfJ+UemItWseDi1JBdBQXndIjg/hd5Zh6qqIGJi6hl5H4k+1UFGzwn2HlN11f2Fmm+CwyuoiAb62VSQYw0HfV0fkl8DW37mrvOmRD8F0Ym664Mky4zT6bdTaUr+Aro/Ojw1,iv:UAOvD3gOCDFmzfQMoDgnyBFB/hvbBMlvVKVCmocysPA=,tag:iMz4QTlCtPIoP2po34Rmcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UFlydi95MUFFSnhzMktv
            NGN2K1VQT2p4T2dRUEVneWVpczlJaS9qYlRFCjQ4TlA0cG9kbEc1YnA0UFVXSVJL
            SnQyTitqTmFIUzJtcUdVZDk0Y0NyNzQKLS0tIGJNTytmSmduZFJwakVXUzdlQVE4
            Q1oySnRxUHRDcktBM215OXZpU1JwM0UKDdq44ElgPj2BVPsbLQk5iFLANSXlvUMD
            OYyeSCWf3c/4+YHBtwlUFUSfjBVvBTVlrbQuYb8WIDw570AtjvrfgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-28T02:41:12Z"
    mac: ENC[AES256_GCM,data:on+DgtqI6JpUGtbEupKNcUKSK6hzk77grITL22EfRxwGbjYqpcHPFBl6W9xeSl1Go2qsKp+hSXmsJu+S/TFa3P9r1LGXVo6GLkhpWcrltg6LzVAtSlC16y6kz7spBxvUHOXFro4vo/301JYkL5udc1MiliQsFJMDYQHfCVBxvgY=,iv:EADs6NNTqYnw0kB5wm99ABMRbwavv8gy4YJapcZrbCM=,tag:DMoNWOZeOr8G+M99zOWTZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
