apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-connection
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:PBVOP9gxEIWfvTLkSApLZTXTvzGXUd5G5NDS09vtKOTYbcqOpMIUqJxj+YVaeflLv2a94XII6WDAhZMB5kq2i2FXhXTIzwHUs8NissbefNjnCBAxOrHU/eRCDnvNW6mWukjve62P47c7V/25OIjnHRVacB3malSx4sWKM38kOBupaT/riZP7xlDfdPC6XBX4vj5KwMHuiZ3yZVYQ4R8YQT/fGPQl74nC0Yv4I2GrCbYOtSgMFyxWEWwVKEcOfFl6c1mp34difruchMGIVaAoKAHRHbjlyrNyYQFZDeF7KYK1jlpjqkVJeWHuQug7Yvd81HC0XsJmw57YWXKgsrrhUCPs9AOnUvG2HcqqSoiWax6lphAINwPNn5BAUdmpebIK8STjRJW6FQcSgN8STI+WjXjUO7rGyzqRzEE3c/HLVCnPRCF2aoXHKQzSW03bPLUxEWRY76N6OCHVwCNzy5sTw2mp+uOPi41IELRbuTnT3PlDRWjmiAwYo4pmodaQNMxkhhl55vXyasWvBNE5vdkwjRbkjw1LMYB4DuRFpnli+7ZqSinS2vHrq3sjI1L46hikGWFjqAs=,iv:XNzKXkgqBp55wN7vbG2370m5ba5FyGWJRG3jFO9hAXM=,tag:wToyRuea1b/40B1yzsQx6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UFlydi95MUFFSnhzMktv
            NGN2K1VQT2p4T2dRUEVneWVpczlJaS9qYlRFCjQ4TlA0cG9kbEc1YnA0UFVXSVJL
            SnQyTitqTmFIUzJtcUdVZDk0Y0NyNzQKLS0tIGJNTytmSmduZFJwakVXUzdlQVE4
            Q1oySnRxUHRDcktBM215OXZpU1JwM0UKDdq44ElgPj2BVPsbLQk5iFLANSXlvUMD
            OYyeSCWf3c/4+YHBtwlUFUSfjBVvBTVlrbQuYb8WIDw570AtjvrfgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T19:41:17Z"
    mac: ENC[AES256_GCM,data:IBO40anO+jNEdFfF76CH68wPT2oHl8NNRhuuJGjGVdGZqFsr+x0vyIdK7oPvupQH6VJ6H9DtY7fDflG9IobOmL6Aqsygg+Y2y/0QzIgYzrL0V19QZ2aolt/bPdAy3CVuGqXzQJi+fkZeftm3O6+Wl6oWxlj8lkSFXLAsugKZ4HM=,iv:dALeBlkpP39ma3MyD56VjRb4AxlEJRvMpTJ23B/LmL4=,tag:KK6oKZY+7kkRfyCq1rvhHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
