---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.9.2
    env:
      COMPOSE_PROJECT_NAME: paperless-ngx
      PAPERLESS_TIME_ZONE: ${TIMEZONE}
      PAPERLESS_URL: http{{if ne ( len .Values.ingress.main.tls ) 0 }}s{{end}}://{{ (first .Values.ingress.main.hosts).host }}
      PAPERLESS_DBHOST: paperless-ngx-postgresql
      PAPERLESS_DBNAME: paperless-ngx
      PAPERLESS_DBUSER: paperless-ngx
      PAPERLESS_DBPASS: ${SECRET_PAPERLESS_NGX_DB_PASSWORD}
      PAPERLESS_REDIS: redis://paperless-ngx-redis-master:6379
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: ${SECRET_PAPERLESS_ADMIN_PASSWORD}
      USERMAP_UID: 33
      USERMAP_GID: 33
      PAPERLESS_CONSUMPTION_DIR: /paperless/consume
      PAPERLESS_DATA_DIR: /paperless/data
      PAPERLESS_MEDIA_ROOT: /paperless/media
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
      PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: true
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_SECRET_KEY: ${SECRET_PAPERLESS_NGX_SECRET_KEY}
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik-internal"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          # external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          # external-dns/is-public: "true"
          # hajimari.io/enable: "true"
          # hajimari.io/icon: "home-automation"
          # hajimari.io/group: "home automation"
          # hajimari.io/appName: "Home Assistant"
        hosts:
          - host: &host "paper.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls: true

    persistence:
      data:
        enabled: true
        mountPath: /paperless
        existingClaim: paperless-ngx-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-postgresql
  namespace: dev
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
  namespace: dev
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-redis
  namespace: dev
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
