# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoR2NLWWhtelU0U25NclI0
            cGRuTzdoM00yYTNiWmFxdklWMjY2YUNWY2s4CjlicGJ4UjhmSnNXMHNoazBpWVpX
            UTRNL3ptaGp3ZDdZMWdVWGo3WC9jQWcKLS0tIHh3TElJUnk0QS9rQ0xLWFlObGRh
            eXhXV2lsbCtSZGNyTWtsNlFDZzIzOXMKTHs94JGm7nfLrWIfKMNAqdscvgOX3S+o
            VXv53uVaaQ3sWC5wqTcHeeF7F9B8lU4JnIMCEtT7Gm5G1JP4tnb2EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:TZDElM1rdCFV8cIlSfCxTb2QNHq3hY/SBVe4xQRhOpZyaA9zIMLOES77Dz0bqXHcPmbVcpXg9xZMemo0q7JgVtpxMmuZ3YZ4la3vNw98gTrLP52p7kgUo0Cb2zFT1TFjIUe40/lYyls8xLjoE0g7IvJsNuYT/SpYBLjK4NxPrw0=,iv:cY4ma2yVrpLBlB4k/oMNE6ka2qkboSAealqHZOW8zEk=,tag:OOSZDQgqrgqPdGGkSBGFZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
