# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UzdMajNTbXZTSXhhS1Ar
            eWZ4eUs5SzE4Uk5rS1U5UUxKeTU0Wk5GaEFBClBTQXJ6QXc3aFJpUHpSWVR0SjBl
            N0paZ2dpSXNmbEJoakJ3Z1FadlJIbDQKLS0tIHpMNkdxMzRlVlhtU09rejBrWGJJ
            UGNJaWlTdzcvUTBNUVRmblkvenBkekkKoNLBax/X9v758T1dpaQvu7nhEd1vhFkA
            xicdvuFrhV3heEks1Td1JEwrKsMZ4IllZje0zjmvelfKHHBRss6uIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:56:00Z"
    mac: ENC[AES256_GCM,data:88kryCpo/9/s17SwZdYKqKQ3Aq98KrnfWMdKUHp2eriLI1zhiQovjOHDhn/UyTq0/oOgma+E5sxCHJE8BLHpMHfTz3Vgq7kAnOcCgUPiOuFn2mpsP8rrYD3bBhJwi4ZH9ERTMb3J5s0o4x9QaJ+WImMdptGr2rz4QYkaGgWPoQQ=,iv:47nVmPYYYBsR9YrAqvZQVYQKeSYvQ4S5yB8B/eqDuGI=,tag:LTdcLN07hZrZf9hrWpQMpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
