# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana
    namespace: monitoring
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    admin-user: ENC[AES256_GCM,data:3I26wCI=,iv:Ncjh1PZHC0SlW+Om046bxRAoLTAHyGHQwYH+HC/Fa5A=,tag:me/+DYTVAbqN28E8zPD1nA==,type:str]
    admin-password: ENC[AES256_GCM,data:ZKgCMthrBVCMXCjmQjewxNvSzYGaXzLVzILXeEvNu3h2lLLa5llu+FI0Ej8Dyw==,iv:YBhrrhT+PVkl7XErl6x2pS/z0iQDaxqUdC59C+04RnQ=,tag:byOkuvJNXvQMYYnsbzPPMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMkw5VWJ1bkZiQlgxRGJB
            dzk0RVgza2pMTm9hSzdqSVo2OHA5MmtQcmhvClhWZjVLZGtxTFc0OGdSM1U0S2M5
            cWQ1c0llenhabTNjN3kwT2Zla1E2bk0KLS0tIGpUYUtPN0NpT3Nvc1Z0MjJaS2Vt
            V29sWWJzWlVaVENDbFFLeDlFd21IbFEK4IVsBbspKMDGiFfycwV2m1c+zaNolkhk
            5frDMLx7MWFQI/bKDlB7T4WAZJHYybgU5UPLsKFLIB2cIPhZxYSetQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:56:00Z"
    mac: ENC[AES256_GCM,data:tvsBvKhX882j0zZFqu198zdvnOQJMxSNO6S2JegCuTETPGH85XdInszeK0FdCFrtqCf8FIyjpJk5cvwYxa3XosvjRKQa1vC08y+7ydTDUlLIoQVJ6cCJdIaUoj2AydAJoW9F71kQ1zmeb8eiuFts/YfUdDSlvrxVot5qsWHmlXo=,iv:EMCgkTtYy7Vvq4Mi0j3fp9wM8DIBnl6DPNS+8IpvO/A=,tag:Ei8+XvgcFgvHBJ/UCcSR/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
