# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana
    namespace: monitoring
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    admin-user: ENC[AES256_GCM,data:qbKYY9g=,iv:72TeaAg83/WKznFYr8Oy3iui/qyipn33hy6nMXcKHKI=,tag:Ygmj0PVLRbBXpWD9e/y3vw==,type:str]
    admin-password: ENC[AES256_GCM,data:iEWlLY6zDcrD9jHRzZULMtmFAnUCsE+OwM0YkpBq15fcJ+1SrP8cqZA8sy1xaQ==,iv:i/ki7LUZm+5sZ9DvltCPFTAKWwwqmWTZLY/RTzooz0U=,tag:axUh4o0eN279WmYajj6+eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cHNyeUVyMUs5Z0dHNHlT
            ZjF0OExZUU1xY1NFTU8xT3c2eXhjajFDYWwwCmtUUHdyanpuSXRFMER3TjRiQVVD
            cmRLNnljNFBpRnlBNmsya2l6QjJBaE0KLS0tIE1iOVhZM2VFSUQxaXNLWW9ENEFk
            aDBXVU94U2hSbnJ2RC84eGlSaWkzSjgKH25aszXj97a05MiBQ3zunAXLX0yedVJ+
            Q99txDwZE8U2HxE0irKkLPfVgJwOCHzKiEmFeF9lZjFwhHbEcXFShg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:tCVj1Jjy0giHt+2QjB8Lp466f8be4tzKD10IlIA5Q0GUYWyjuQjYFOmCwQLbmoAb2DA9iNlsdyEa3xjbpVtpRYynUen+wzPWR6XsY1WEDheM2Ov74874y1fXUCgSbDngORi6jkAjVbqK6UCHm/wCcSXA92MSL7GGwx9ck5Nm6B0=,iv:Pyuo5oDeGwWcQTD8YYGogOlPVg6aD9UB6YGAptSjBQw=,tag:PdxgRdmG2vXaHPOLaoIFkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
