---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data
  namespace: default
  labels:
    app.kubernetes.io/name: linkding
    app.kubernetes.io/instance: linkding
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
