---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-home-emqx
  namespace: flux-system
spec:
  path: ./kubernetes/apps/home/emqx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-gitops-k3s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: emqx
      namespace: home
  interval: 15m
  retryInterval: 1m
  timeout: 3m
