# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    api-token: ENC[AES256_GCM,data:36j4YvUHiNLwlMB3rOCe8vCCV8gP/tuAb5cnfAGX3QrUrLYXQw==,iv:danfAhlBZChL4sFxDBZNAKK7HTUuNtSLziPeKsN0+rw=,tag:nqtTkWkzyQJXbucGEJIcYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TDRxelo5M1hiay90M1Zo
            dFZnZWFqK3Zic1ZTbmVFd0o4L1hDRnZGdlJ3CnZDTU5haWpNNi9lN2NpbW5iSWc1
            TjBRdFpaTDJVUTcwaW1JeE1SODkzZ00KLS0tIG9ya3JnOERualY5aVhyZEZ5UlpR
            a3ZDcjcrcXRjcVhOY1hXbVVFSWtUR0kKP0uPTfa+5s5otPOEm/l1Czc1nUojsCkP
            JJLv1woCB+H6dH4eInmcoWJC9uUwVihBjZdj1I6cw3TSS2SgOQxPjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:ls1T3KuTlv5BdLUsNMzApRHEyi92Y371SMjxHnPUlTxWzccD3cW+PhHKdz6nn3kfX20DkByNFf35ckVg3R9zj3Iwmc2chx4N1ixjy1c2shDXlI2YpdCoO8YnWQMTQHD4RYfe2S8SnbzUhLgejiNcTEaXMFdqzoP5CpXVg2jrnvY=,iv:bVUEr0DyeUEt9G2JODNvyuhwsMqwQVqaA79hpuyuP10=,tag:3kb7VMTGVx9U80EMwu2/9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
