# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    api-token: ENC[AES256_GCM,data:e1xGh14r8thcMoDmZT4ggm0T5grTpo7v2A/Jd0EWIUmWehCIJg==,iv:wVbZFE99ZzpHBPMzazqOt8mf79efeUPi9fO7mFxwnvQ=,tag:uEKl1cjfXnoM1ln7AKIjQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSTFlVUJFdzFQaXQ1a0F4
            MDNzSzlObE9QaEhDVmpVdVo5REJqcjgzMkVnClRzZyt4WWVoZXliRUJxcEk2a2Nl
            M0VtQ0l3d04yUUNYK291bmhUL0huUWsKLS0tIElkN29YRHk1dE9ocmNGTEIyM2JT
            aUpqZldyVzJlSG05dmtTVlJHdUlQWUkKVv2lJBI75fFQVKNLTVwolLn8DX1l6ta9
            yibWOGnm6TRPDcdRiqQT0ln3QjgiH9lEvkbgVYKsMBwH1Y33nR8zfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:55:59Z"
    mac: ENC[AES256_GCM,data:rQBMR0KuK9uYhELUiHzD+2S5akmIhU/kqDlZrLXRgfwmFt4OXaNTCoFvuNj1rltumA/J70PRtAuneoii1NSus+bX0Okz/2J2IrmZ+mgDlGBDJwnrjW1HRvFzgWekw8lYZOiqpCn42rWoXmKwwTm2oGBifZW5gs0pNTg3n9AqHNc=,iv:+JzkJDQM6CV0L/XMoXLiavlJ7OyZMs8vKiEFQo2SvdQ=,tag:A6MtO8HqrvOjT1KPzaworg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
