# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    api-token: ENC[AES256_GCM,data:1Iopt1UNZQ2D2Fm17Wd9mdaoGBxj5YilCoSftE9Fzk8MGcUgZIUIBA==,iv:jT5C+jKSmlTQ4P/r4aVAEcauvjPO15G6ey7AuDKM+x8=,tag:4Z/fxW6bzWWYsMEiy82shg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TDRxelo5M1hiay90M1Zo
            dFZnZWFqK3Zic1ZTbmVFd0o4L1hDRnZGdlJ3CnZDTU5haWpNNi9lN2NpbW5iSWc1
            TjBRdFpaTDJVUTcwaW1JeE1SODkzZ00KLS0tIG9ya3JnOERualY5aVhyZEZ5UlpR
            a3ZDcjcrcXRjcVhOY1hXbVVFSWtUR0kKP0uPTfa+5s5otPOEm/l1Czc1nUojsCkP
            JJLv1woCB+H6dH4eInmcoWJC9uUwVihBjZdj1I6cw3TSS2SgOQxPjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T17:27:01Z"
    mac: ENC[AES256_GCM,data:rtRYvXxAEHWjzsdiNZjYmP5p98cQ6rIHulhDXSxo23gvO2866haPSxNGnI4yonw6mhlWluOUDDfs9ZL/owgHBe5+JRp4KzLILlO2yLHM6szsNiqwePgQnFKaQdIdtDwlUELrZDwrP+N9pJ7O3NspTtT2NVv0djYoRbOKkeFrMoA=,iv:mO+OoM0oP5y5CA90njadIZ2tUTSYtp84K9hgyzK7Jdo=,tag:6Ir58OtfK+M4HHvrIFdfjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
