---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zwavejs2mqtt
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: zwavejs/zwavejs2mqtt
      tag: 8.11.1
    env:
      TZ: ${TIMEZONE}
    tolerations:
      - key: "arm"
        operator: "Exists"
    securityContext:
      privileged: true
    service:
      main:
        ports:
          websockets:
            enabled: true
            port: 3000
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "feature.node.kubernetes.io/custom-zwave"
                  operator: In
                  values:
                    - "true"
    ingress:
      main:
        enabled: false
    persistence:
      usb:
        enabled: false
        # mountPath: /dev/serial/by-id/usb-0658_0200-if00
        # hostPath: /dev/serial/by-id/usb-0658_0200-if00
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi
