---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-default-postgresql
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/postgres/postgresql/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-gitops-k3s
  interval: 15m
  retryInterval: 1m
  timeout: 3m
