apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-secrets
    namespace: default
type: Opaque
# seems to need both keys, idk why...
stringData:
    password: asc80989c7d89c7a07900daca909a8ss
    postgres-password: dsac8a698c789adc798d79c87v8nwv
