apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-secrets
    namespace: default
type: Opaque
# seems to need both keys, idk why...
stringData:
    password: ENC[AES256_GCM,data:ygESRieSIX+58Z3F2DJEkIHj8RLzAWPrxgNuSPCJuus=,iv:bDJLC3/uTn5MOGNHskcXc56NudoXcd+PS01wVNKlP7o=,tag:p2vf4904tgkpSwd3/lzMfQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:RwvLoXmRrpYGqKLDI8zwlvqvoJ1dE6/MPWvmQsFb,iv:dUrgdduYinAh9HiuW338ugCwaSQeJ+qqEG6lrpwWx7Q=,tag:JyZfpa4wR96wzwlo08K4QQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNDFITyttMTdJVXg2K2RQ
            QzI1L2NKbUMyeHZNOHJtT1I4d2dnOStxNGowCmIzSE5oMlE1WC9oaUxJaEdOU2U1
            V3RySVFIYzVVVUJBMm9rem1VQnpaV2sKLS0tIExwVER4a1VZY0ZzOW1EYzd4Nnha
            R1VQNTNuOVZxcUZseTI0UkhCZmNyQTgKVohPLwNhnbLYYc+EpbDZjC5umDQyP1/a
            1ZlbkpZUhNxEMoCl4EF8tQ14ZwOv/xYfaUZPvfAO2W0JctW9S81f7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-30T11:02:32Z"
    mac: ENC[AES256_GCM,data:5a5J2mo9XPX0ODcIheRzMVelmRvmhKR4aslZjvP7DCC1DZZ6C4jVKYBVYBd20llMZ+S3a6IbHFbGGE6z+ImSv+BVJuO29pZauJr7GGt8h9RiJN4oGUpXWwcnGqbQTIYsjqHj4z2t1LncAmoVl4JEofPRRnJUdqg1XcZMJIG7itM=,iv:gquJI3symKyZWiJ1BttxVrtlVayI24iWAky9KgJ4EDk=,tag:SWLZ/z18LU74E2wMIAXN7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
