apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: null
    name: wyze-secrets
    namespace: home
stringData:
    WYZE_EMAIL: ENC[AES256_GCM,data:KKb3Z6mC7R7hMHoOonn2Z+57BlL5P9ogMa0wKFQuadjV,iv:klFP9T/YyOomand6IDPBEJsHj8ZgQC2h+JrXPVIxkVI=,tag:VUxsUO5/qMcfDaDZDHAmzg==,type:str]
    WYZE_PASSWORD: ENC[AES256_GCM,data:GMD5Qsyy5YH9jjWT,iv:pmQlStq2UBOsv0syiirHnzg9Xu1B5/2mMwiEqKiCUtA=,tag:9O9a2jX+NWFxrbTaZk5lag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMEJoKzRpN3ZtR0IrTEpk
            dTRyd0F2QXBIang5YzhhWFB4cTNiMFdCWlFjCnFmRDFWaEkzWisraXA2bFBpYm41
            cFQ0ankveEVtYXNFK2RQK21LOGFacUkKLS0tIC85ZlJkU09NbEMwTzVIWElCakxh
            b2tRRFNReVBoTUVoc2pEUzdQQ1M0UFUK5F+ZSnUOYNC9Y2/OyrVC4qPguPFK2tiH
            NyI3q+gigGrK5DV1XfNY9ZQPVtxtvRncM2LIiVuYkzqI8c10y7jc7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-30T14:30:16Z"
    mac: ENC[AES256_GCM,data:BswmLszU3JMl3yL/m8odg9lsxDldXP/9O1Rw/5d9DtE0bLDDsD1SGKNpgRMkHdgdto1Slt/eVtOIIRr/qtTfTMSmxu8qaFRLKGQpGpEKd2ZiY4gLCCj6xVInm/LwDNdLxZ04sO98KEz9wZ0oFV3Lt5Kj7gZUN+Y4iF8JhIyxRwk=,iv:gcW6oSIsR5GaqxLE7cRraYPc32y33KTY2+WOAoK/P+w=,tag:VhoIjANa0TR4VDNN6XqbTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
