# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XuFxuizmOOr0ZOfvIWGtuOgNuwddyCyJ69ab6n/wlQP0Qhsti5OqJw==,iv:2xmxf7rUdgOJM5tRENPlaYnLlfCbWX7NtfIlZ+ahwrM=,tag:ykIaI20QQ01zJvOfOKjIww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVkJqNStrSjlVWDV1WDFD
            RWdpN3ZQMzdxNS9jeGUvZy9oMEFkRzczSUFBClRXUWxBYmtOSU1qM0FXS3FmUXV1
            K3o2bFZXY0tBUG9hbGtxZlNHY0traTgKLS0tIFNBa1QyRWE0bmlSdytBSURENDEv
            SkJXeGtRaXE0YUlkclk2eG04UGF3U2cKhBk+nFs4LsBaMzpKg8rJRafrFkMnx51q
            LIlCG9VV8QQA0sLfTDBmouaof4erPOOVKDgAYm07wLAiueo+UvJa1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:Lq7hkomaug/mwQxW0xMQbovXfVhvmuavrh4x/X3fLLRFdyRg2E15ZGok3+TQ37g2g07Hpa5i4aQ7hzu585iIe687ZEds/wdYOIolHsOeh1nuS4f53zD9da3uhzhVmTx/ixzfPd+wDFsVFmSBuBJ3w80tMcqEkOnPF6lZ0WIaWxw=,iv:ouHx7Gr2rtfsuJ6Df/sYnDdzTv5xvYReDWTNKtMtmN4=,tag:+k5qPfAFaK+XvdNIewyE3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
