# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7J41reXJg9ZZFLxOvj9ohvvdqz6tKx+GTmUEJxdPFqhamKMCzkwXcw==,iv:Sl97V8bKI8deKE8mzzpRSn+XKrOT5LfSch9CRdgF1iw=,tag:Bu2GVSVhlWYIRqnaAziRHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Sm9CTnpyaEdZTEVXeWlO
            cXhKTVVOY0FNbjF6Y09aZk9LLzlvd2MzUzNzCjdZZ1BXdWhMWkNHTHltRVJhQmV0
            dHpzSDVvdUtvQkttM092dEhBdlcwK3cKLS0tIFErZlU5ZUx2OERaVmtOVDJqOUlU
            SUcxN1R6NVp1enFGWnJyK3ZSb05NNlUKBCyuwyOJ9hSDLuMeFdgP3rXDadQSVu/6
            FnanZFBL1Lr1pxjaIWm5hnG8cNux4LhWSrnIX3ERzLpESYCmjB+KIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:56:00Z"
    mac: ENC[AES256_GCM,data:C5uzG+D5AIFkraHMtAaKH6RIgr/xGFvVObN+WHxXdIRtVsaW6UMXeApt4L/xWVA4qUa14MJ0o6JHeUdA0AMzUHRzxmRUIZL78cCPegkvUT/aAu4nEGIfB0DI94W8H5TjXE8cfgVYf7U2rFp2gEseKAXFZCU/ZP1Dwg/tUpIiS/s=,iv:H+2mC9xjInxgX3BItosDIihVksJQ4aAvg5ZvE54rbIA=,tag:oUnfooratJUQqjICD4ogUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
