# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbU4yZXQrSDNsQnM0emhU
            eWo0YXVzT0cvSlVVMCs1cThVWWlyK3VPZVVVCmN6aTgzbXN2WEdnbG9hLzdmYVF3
            YmswYVpOa3hjblV4SFdNQkkyQnNBUjgKLS0tIGR1N0pjRGtQODJKL2gxTGFWZEZZ
            d3IwamlhT2Q3V2NnODA4cUN3b3JJcjgKu0UkiL8tuMMK5Vt4hI36L+D/r1KwjbjC
            J28ohqVMVnBoqqLsrodFLrQLw/vszbIe2qYPtNeR4Qv6ErOEBJj3mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:56:00Z"
    mac: ENC[AES256_GCM,data:RYOvUqldbPpmS30CGcEUS+5bNfw5++/0V4xvumU/au0Gdj51RBQUwepd1H+mczPsi2mtA55g4I6/uC9OHbmCR33acRdMh06O3HwjY/Xc5KSxzLb6QNl4HGgE2dtXHZf/F+zMn6u7TzsKz96mYwuXUVGD779loezBBySLRc5jygo=,iv:VXtfzTIlqJ9eCxce5oYB00kH8x5lfEnpeZ6a+ESBJ1o=,tag:gXB9NeemuPpmazQIbYmioA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
