# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOFBRai90RjNmdG9jZFpV
            WGZNdi9xY1NyMmxLN1BablR0VDBxbkVCdHpRCkd1Qi9Dd1pQN05RRlRVOFZ6Ukps
            VDNIMkNNMnJNM3ErNnNJSFFuUnJQcjgKLS0tIHF0Ym1xakZIR1Ywd2VRcDZzM0tM
            dVcxeWtweHlxZ2I5eU9BVk9SYUZHMjAKXsIG6VYU8DgSu/PNm9xUN8Y6Tm+DzcpR
            qY06sAStouFhVI2NTYGecPaIO745cjAWnr6Ulfy+MLCjuGSziOoSng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:9lenHvtIJSGqd2tg2/+bpGmmM2tQa+6fuUEqpNGK9jrDyKfrCxjn2M08yb0OqLZyWz8cC/xK2EUogneUtGLJGZFKUOqnxPAPCJxEQab5mjOD+K/unE8Cw9k62JvZvx/pGUUhd1DJAabdXIaVExs3tpS1a7M+XYx2bga09ceZkwo=,iv:Pi1dqFOozN/kB0qUlqYYCa/7aMKNr8gXAYOJ4VTJ/gw=,tag:weDepqL2Mj3YYUu96hBqvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
