# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    #ENC[AES256_GCM,data:WpOQjXCquC/S7M7M6GfTh1Jkf7CAosMfnG8YQi/Ld3Mob1QSncjYy7qazDeCCYXDHpvZGUt+jKZ0DyyF4u4wLURBGaKIVrwt0zzO,iv:kt4nyseNsWiIoyp3JSGHMFQZVkJN/Mp8iMIqJ0c2k80=,tag:dyO4p5UveYQFi9wswKCgKQ==,type:comment]
    adminPassword: ENC[AES256_GCM,data:RAZIOdy/agEdPnCotK5wkv4qFXvYFEyWq1FI3lbdPbh80cxeOtAEhy6mfqvJ+S49whzHFitjggxsfX2k,iv:W8HxocelCkaL5+T+88yrJxa+hnQFIR/V0iTvTa/ZvRk=,tag:/trWmqnK5IMzFqcxxadYEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYjNZUGVzeVJJVHZoYkNX
            MnVGSlU4SHZXYW8wL2dKTzJPUGhNNDRRMkhJCnpIeTVsdHU1bmowQzF4WDI4OEU4
            K3Y0dkY5OHRYVW5Oc2JNWE91b2NaQkkKLS0tIGpLenAweVNPRUtXMlNjTWlpZ08x
            dnpoUGJuM0xnM1BPb2Y2VUQ2elA1cmMKxYxvDmmLElt6+Sr38vPUVw0AMurpgSuj
            AcREcLCsntpzIeg0z4tO8C20wCrWItVuFaoCMyjYmRh+ixiIxRydKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:56:00Z"
    mac: ENC[AES256_GCM,data:7JoRYzisrIGYqCV/eaxQlIRDm4AVzUblAfhIbPp/M18E9CR+tZ+o28+OlgaMjyuR2OTZL9KkF3ZXr80FVWlhv02hiHvj9IqTnc9YSN9bnF0570+Ml85VgDMaxmEaK87o/q9CDDyDjndnlD82VB4Zv6Pwc2b/eHcHxg9/RLnqrE0=,iv:eiPLxtgqK4TRRHO749ixiDBiLHk6mJsZ2Hy6e/uQE9k=,tag:yeNeOYIllPSlvVQ00GcMaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
