# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    #ENC[AES256_GCM,data:mTIlk3VBnFbEhHzyp0F8l4bL1M2/ZXYHQKHmHdG+janMIeDAOnr9vHp7orpbqhJn0CGBdIVyxdz6tvE6CcBlI2qW1L4rMH1sImS8,iv:8D8tOhJAZKwoo6IXpZJtEkjjRWExJ7aJbQjV6noGZm8=,tag:BWCNriRYaYybN2KuYn14qg==,type:comment]
    adminPassword: ENC[AES256_GCM,data:nf/pbAr1wbBM4KCIdIEtFst/kOf8rqXaUQWgpl+6K5hNf/X/A+3f1eTRnxbgSXfehjKz1120daw1JZmd,iv:SlDNM5xwMNrqRlIPderS2KMM6uo7tzyIXe3xq/k0g5E=,tag:sxRpb339S+M5chJ8IpsZtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OXhZam5INzNvZ0VXTFYv
            ZmRYWVVwNEFXY2VMMFFmdHY0UURYYmk2VTM0CjNqckFJRDV2RW93L3Zqa3JVQW1E
            TS8wOExyaVJUa2Z0b1FzVjhQQ0M2TXcKLS0tIElUTklraFNES2NQL0Rad3NQY2RY
            SHV0ZTB5WkQ2b1kxRU9nZXZodllkV2MKREYza7P499CM+jWQMSMXPbRgL4Gdj9ko
            LCNbm3XPJGQBP5B07V2oNU6hL+/UNuwcKMVQ8H8i1n+CdinpABFvUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:Fa8LlubNkRYMg2ZWqeeIPAuenjZPyTjwZ82OgrzBZ082/AfD4U3FrywG5ClICu6o3ZDVhbz0ouVPgg3OrMnMG9T6cPtfeEz1ViDJQNxwjwQilblIjhgzlQCK81+tb2E2dYxFZODR0Gkxp6VjUAS4+foIsvq9w+ZWvS6BSUA7+Sk=,iv:jbacN+QJVRdqqJqhiuHBppasImKL5V+EM/4IAXTm/Uk=,tag:3as2H8r4amWSEwSY7Bm3aQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
