---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations | Apps
  - ./gitlab/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./paperless-ngx/ks.yaml
