# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-basicauth-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JZPRWw8=,iv:pRMjW60Ec7XFuLuDdAZBzpuDXOc1/yqu+HMBtW1J5hs=,tag:U2HkM71b/XK3+Y1cAgM1tg==,type:str]
    password: ENC[AES256_GCM,data:86OpUBYCaeOQ80LcrSWYcy0itPFOfsbBY4FhfA==,iv:nCMd6au8FCWFi13P3Tq3fOP0b4CmdiKcqa6SLvMpvs4=,tag:89CVbLNfNrHWz14j4zu7Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV1RaOGNnbkZHZ2ZjMHdY
            cTc4bXlpNXhFT0lEYjdBUDZmT1E5emI1bW1ZCnZPQVZnSTFpMXBMZ0pMSnhwU1o4
            SUhYaG5yRzg5c2hQOFVIODNBeEtESFkKLS0tIDRYQ3lkWlZJS1BxRFU4Tk55ZzFy
            WHN3NHN4K2UvVHdVRTFkNE1jUGJSUDQKlZRrTqN0vzWE++Vei0oDwYdhxQDfP1wW
            V4RpwLZF+CFgA4p8oQqSunEXqWfNmRiT6sRG1bWl0aZQYSrM8gxnvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-29T13:34:52Z"
    mac: ENC[AES256_GCM,data:Y2b/10osJ9YljUifcfWck7ErRRJn1tpAaXkvN78EvmL6Aa1UI2qBocptH5cuuepWm1BYz1837OwbQk6mGV8aNJzzvg0207W05EgKTR4vYu+/qV06+Pn+u6FCHYCvtUpZ+rfO78LatRkF46jxeiIiY7wnOJtgQzeAfxpNsJM7mCk=,iv:WG89Ag/3bKlEignBYGXJXmfwQ04H8jKrKTSc/UaJrRM=,tag:Mk7xOhqaKW0IeCWCO2ddNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
