# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-basicauth-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JZPRWw8=,iv:pRMjW60Ec7XFuLuDdAZBzpuDXOc1/yqu+HMBtW1J5hs=,tag:U2HkM71b/XK3+Y1cAgM1tg==,type:str]
    password: ENC[AES256_GCM,data:YgYt01+H6GGrIp/Cv610a5FpdxnFi4++pyKIp/llLNklFiSaJXU+8S36ANP3sw==,iv:qZ94AV+wnPTLxMOJ4n86XaqatYweJqhezUChvro4f2c=,tag:4FQjeh7nyWm2BLieWjaTQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV1RaOGNnbkZHZ2ZjMHdY
            cTc4bXlpNXhFT0lEYjdBUDZmT1E5emI1bW1ZCnZPQVZnSTFpMXBMZ0pMSnhwU1o4
            SUhYaG5yRzg5c2hQOFVIODNBeEtESFkKLS0tIDRYQ3lkWlZJS1BxRFU4Tk55ZzFy
            WHN3NHN4K2UvVHdVRTFkNE1jUGJSUDQKlZRrTqN0vzWE++Vei0oDwYdhxQDfP1wW
            V4RpwLZF+CFgA4p8oQqSunEXqWfNmRiT6sRG1bWl0aZQYSrM8gxnvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:12Z"
    mac: ENC[AES256_GCM,data:M/Byg9mvSqCd+tNq0cRwnHe9XF3LavpJo4ukqPgK+lEwpR48rlSm/Ro4QaG0s549wK+8Ao+1gQS2CrDfJlSq3W6L894lHDF7A9fMCKDrKDBnAw53DLaV0TBoKALok/TnmhIN/DvxdLUdNy4lLmocLlFyjAy6xnvG/K1RjvASrhY=,iv:qeeAlpq339NUnJmwCh+aSlyE64lsLuJ08eIvOEJvt6o=,tag:+pmvIVZxnkrYr/8IQrb1Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
