# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-basicauth-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JZPRWw8=,iv:pRMjW60Ec7XFuLuDdAZBzpuDXOc1/yqu+HMBtW1J5hs=,tag:U2HkM71b/XK3+Y1cAgM1tg==,type:str]
    password: ENC[AES256_GCM,data:AHMD16UyVzUrTT6f,iv:K3YjXvMEbSEx3zz5XNrFELWBfV8vtDu1P4Knn3fy3Js=,tag:c2PSNhGozPKS9qj0InrL6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV1RaOGNnbkZHZ2ZjMHdY
            cTc4bXlpNXhFT0lEYjdBUDZmT1E5emI1bW1ZCnZPQVZnSTFpMXBMZ0pMSnhwU1o4
            SUhYaG5yRzg5c2hQOFVIODNBeEtESFkKLS0tIDRYQ3lkWlZJS1BxRFU4Tk55ZzFy
            WHN3NHN4K2UvVHdVRTFkNE1jUGJSUDQKlZRrTqN0vzWE++Vei0oDwYdhxQDfP1wW
            V4RpwLZF+CFgA4p8oQqSunEXqWfNmRiT6sRG1bWl0aZQYSrM8gxnvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-29T13:38:32Z"
    mac: ENC[AES256_GCM,data:GZ0pMR87hOrqYhpsn4xQ6pxvE99bmBohfONblxDmT8S8aTCsYZjeQmgg5oJpf6nuTkwWGw9JV3jEbapw4RsgrHvmcWUzd3n7BD1EHUa5Dcv1qdHSUoJShAgFbPoQB/2qIE1YH1E14Z4sCjjyL2Z0EyUT9qd5f3xVlSZ4IatVn7g=,iv:xh4QFIlNnpEUS5di/jAtLUaN+RVDYnUj+oawthqkkOw=,tag:gCO4g36MP44Rcq/ZPxpIww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
