# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-basicauth-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JZPRWw8=,iv:pRMjW60Ec7XFuLuDdAZBzpuDXOc1/yqu+HMBtW1J5hs=,tag:U2HkM71b/XK3+Y1cAgM1tg==,type:str]
    password: ENC[AES256_GCM,data:8XF4bOTPeGLPZ0n1,iv:y5PqljbvqkG5vLcE/1eR6O/9Hqpd22/VESb74aBrH5Y=,tag:UbJeK3xnitSs3HuYSM13QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV1RaOGNnbkZHZ2ZjMHdY
            cTc4bXlpNXhFT0lEYjdBUDZmT1E5emI1bW1ZCnZPQVZnSTFpMXBMZ0pMSnhwU1o4
            SUhYaG5yRzg5c2hQOFVIODNBeEtESFkKLS0tIDRYQ3lkWlZJS1BxRFU4Tk55ZzFy
            WHN3NHN4K2UvVHdVRTFkNE1jUGJSUDQKlZRrTqN0vzWE++Vei0oDwYdhxQDfP1wW
            V4RpwLZF+CFgA4p8oQqSunEXqWfNmRiT6sRG1bWl0aZQYSrM8gxnvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-29T13:48:16Z"
    mac: ENC[AES256_GCM,data:HCS2OIQi/CZOXIv5xSo6qwgPQ1iTM60EPVyfQDEZJ3TMsoXfOprylY4gReeGOFc0MNLzKZNknOUYGg6ZlgnhAiJIBX4MpXEAgATOCwlJEdbrUJG2v/xYOgRfpLeEnK5vt5YVG5Z2Rut6eTWjQU6R2JZUcpx9V1qlhBM4pggEWyA=,iv:1e6mOsXlxis9YbWMwuVzrjworTfHBEK74uViZo4gSGM=,tag:/rMIgA/Xo49/ZOhnQHyOAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
