# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-basicauth-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JniWlTE=,iv:0IolUernw48e+pRRWgDRKxx58AkiL5KJa9sYcfOASJc=,tag:T6whGJCRzdpSZmCmyqd9Qg==,type:str]
    password: ENC[AES256_GCM,data:VfmjKoTzd7wwoiDb6laOU8dj2DBZtLop0MBgrSTIWASenhtti0CqO0G3ZQUy6Q==,iv:FPNZJNvYYNbPAGINYn0jGSMZvcirOIqxQ6GPTQFH+7s=,tag:GPMIwuMD6hWqwn180vqL6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa2VwRDlsMk4vUzZmZnRh
            Q1NBNnJJc0NvTXV6eDhycUh2alFsZWxBdVRJCld3Tk5qanZPeGNXaUdKdXg1dnBz
            emFKSGxFd0pMWVN1dksvRWRvcXo3N0kKLS0tIGdwcGdCb2NOV0ViUDBFczNyMHE5
            bTBuajMyb29QS2NlWmlZOEtIaExodm8KlODIONXlbc5ECKXXoWrG0vyse0wagMIl
            ENh1KAs3yk1idVSfjq5luwadL8sNIGKfJVBdtNojHaCxodo2inE2CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:56:00Z"
    mac: ENC[AES256_GCM,data:oCF/X730c8h4LKUn+99RZUXUWwqTSXm2b6kRYQ1l5MfJrI5FMMT450qB7rqvo1ZIBFNoUkAfPHJSU5QxOsJpGfa7jgdaiDC26T3qbtTh6Pe/5RVYuznY8un7f7XlpU3UzDG83QqOqknbUBXntCeQUZRp2tR0cJrza4DFmToID+g=,iv:qKZB3HOTHUBDufB0msc6kE5ngfn9xV3HYiPpc7fN8vI=,tag:g6O649slBtdm9UQJAXhZrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
