# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-additional-scrape-configs
    namespace: monitoring
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    additionalScrapeConfigs: ENC[AES256_GCM,data:hMNo5jFFXLmtFmHjjRcpH05H36rb3dMHsGnTcVWPuGo2s8D5+mO3PKTb0V3LMwx87z60wrQvttdX3jXYxxi9NSoquDU9fdg8vWehom3glw0Xzb3pdwhZA0FVvZZDFLhaOJo73Ox7ZXUgKEbYO8hehFpHZ9utrLGDCoo8GS2EPrmDgsL9R/lQUxH6ppA6KxQ3JtCaYJLmNHdT08isiMjTHJH0ZkFeqS1jcqgtYAEd9t/asA4tMS50DhpVXOvsXu213dK5kMegji0gkuREPFH5fXcSUXfumAr8LxgitxIf/vRGYEp0cCvNU4FVlv68NsxQsVK1RJXwzmUhoyDhha+xFw7NrCD50ke48PUmIbUveeehqwzAuiXhzxPCS/BpjmjKTqYE/FxdBXBAz20qgimR7PlLx/Njhd67L31mypRwjzjsl6xj1AfPpOSg1tIO3ioIkQxNDkuS/8vEqFl36lX86VSd77Pu1dcYZfigWd+46a7qgoTHHE4ZCPhpnAXqTBgr23Ok/y6DvWz61tafdJNcSKA598pVeDb+KBxauikvaJe73e2OxqA94VddmrMIgsrHvv5AlTTy78qiaAOA2xTVrGDHrn6Gr1UC3EDNSb7mX4hDnWfMKLL/wJKjxinRdEqg+lLG7pe7QfMvArIKLa5uFuXKfDhkT30rY+T129/qFrgjRa1lhx++zfzZ49+66DUJ0bNiW2vPJSiWPI5VWGNmIUe6geORVpysYV+S0oCNJ1XKD2sw99BTRzRaNxp23gkUbMysYrmiOynG9vhk3ckJju27kyoyLkbAcxtBzbZJgcdgEENkSMB+6uTfOcyAnQC2ParXG8IJ//2k/sA35nUhHlWRpqi8WRAaHA0zAFRY7zOkAolD1lnWa8o5muyU6BuIGA==,iv:HWNHpK4BeXlzIKg3ybSdzBKdLXbd0nVlcgkl9H+pxwY=,tag:xM0rUY9pbV0fse05yi5XxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUkhuN29iZHJXbjF3UUxr
            U3JFQWFrQnkwTlUwQ3NFWE9CUjd6TG1rK2dFCktoTnIwUTBoMDdsa1g2KzM0L2Zt
            elQ3Tk5OTVNJaUx1TE0reUFDM1ViLzAKLS0tIFN2OGhqRzgzaDh0aFVGeFJYdEhK
            SU5Xc1NSSUVRUmtCYnUzWXNPaXRLS3cKY+ZDol/0nXTrFYfwHmlu8YO/1mTJvJS5
            Jxh5e38mF2yKyWFaOJZFaKBHjoHnWZdCXt7QQlfr7qa7AbLReDLXYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T04:12:16Z"
    mac: ENC[AES256_GCM,data:bAPEKg4OH8MvYVKLVuxUQKDjBkGDMc7Taae8dtY2l0uJo9fpZIUzvsTHyxPQ65M+L+rU6wg1txgEzoLs7d6OKNYkl1lsEye+NQtl7S9QR6fLsHHCwmdd3FeenRiUuH4vmImKxgH2Olb3R6oQbBzYm1qlwxrsZD4RpNJlbSBtLYg=,iv:gfXOP+7dlmxJFgo5OGaRCc/+daGuq1Jn632KSQJqWZI=,tag:9aBOq+j6SxfmI11zJrEf+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
