# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-additional-scrape-configs
    namespace: monitoring
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    additionalScrapeConfigs: ENC[AES256_GCM,data:Htb8XIoXwr2AUmOHpQQFrlVVezPa3VwXmhyPS4Lb7/UqEb3RQeahonf1+3PuLt5rn22m6s5brYupZGurAOJQuRPzSB7RgSQCwWMQLJt+tnQVSdUS6IeEkxcy9qZGj0Wm8hpv8F8M2Tbdga6yz5bfmojSXxUVxL2Ua0ZTEWQAuEkhUO34/pvVg66prYlHfqJz/EPVYkCcv+SO968J+3sraitOxMCBrG91gjp88Lg4oHHUzNGc22+GTUVokoOUZNsjXdi2LHcx5PW0ZER6wLcNzMVb7nVSmgZ3i/IsXuSwcdIMt9Iml1+ukJgI8XN2DQBkrPQUM7cQdy74Dp4m5s0sAD+Z9+CrnvqqLUd59levRQttGL/VoyvxlHAYTRl7X4vOGc74YaugFGPo4hooBISv7+M+bLw1nmAeYygL1ODjbCNcqv/pw/ay67i0vggk1SV4F++gz3x6fjewBMox+ElHFiTLGEBkIxWou2WLil5RiZ3BDjURhU0RVHdcX2dTE357KSPtK9orEMBHsnN/GEXtwpTHK+Rv4QY6MJsZCxcLhXM56jRyEI4OE8lTKbNffdxykPT+wxbXDTWXyKtGtyFRINsmcmRXy2BF/cJfBjYTrqhc8++5sD+ZbChZrqqLjGISGe3nXnjcw1jTQja+jM8FyskUNk3TrQ3LeQXSbHdQUXYBIBT4SfmBTYLzanJzU11pT4f8+gUHFrvXtSXThH6JhWrXS77X84B+UEiQlhoszIUA6wcOHNZvN6hr6ByZHgHonC/bdkE8jIynkKvJ1GTzf415JaTIByQJWYxQsjEeuPKgr664UHlh1FbYDec5vVpYilkbddGFKszvBu2sA6mFw98Smxe61/UcGRHd5LJxzrlQwUcNGpjY+ozCoomQ2odqIQR2uAW8LoryM5dyeN8gwKwjol1oTvZTJTqAEwBNEbp/c/B+vlAkYHfkXf0fub1CjCOoWO1+6bNsmfOP/MRGuqGRVpq8sSqRdRue9zPCdjS6mXpE10t7Y+5BjW1Ye3OhFoZn4Kinxhs43H+HgagphsD6/WIiPd8CIm7AAsdUUQg4nLy62zaDLCBXSO1YRy2DUMCNaWxTitFsj9dnlmFm4xqh6A7x46uEtKQtvBS7VoZVn1Z0F6LIakqhXfQy+Fjzwj0PNZyb+A79VI66vvf0hl7/PJGiaV+w3vyxLApeQKADHg==,iv:hdFEpHoPd6XWDdfEEw2Edvj8pfMENdLpaDQzyCfKQPU=,tag:2UqMfw9Q4z2pGADAu4QgyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUkhuN29iZHJXbjF3UUxr
            U3JFQWFrQnkwTlUwQ3NFWE9CUjd6TG1rK2dFCktoTnIwUTBoMDdsa1g2KzM0L2Zt
            elQ3Tk5OTVNJaUx1TE0reUFDM1ViLzAKLS0tIFN2OGhqRzgzaDh0aFVGeFJYdEhK
            SU5Xc1NSSUVRUmtCYnUzWXNPaXRLS3cKY+ZDol/0nXTrFYfwHmlu8YO/1mTJvJS5
            Jxh5e38mF2yKyWFaOJZFaKBHjoHnWZdCXt7QQlfr7qa7AbLReDLXYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:YxPZ1f8tvSUxKth1K2YRuxMkyRllGsH/hZTQ+8BwJHOd/1Hvm3Qarp8zC967Z7c1OHEhexN22XnHp6pdYGZBEGsLAb8DHjduPj+Sh6hjiimMrYTE8lnNCZac2887774lgLxhysWNQK/5ZakYy4rcohAZyy5Qb0ui4UjPjN/gyO4=,iv:oxyFl9udqCmII8f1kvc01fG2heNN1ENNEDd6ex70lbw=,tag:ikyPI3JXMEID6pdmx5hFqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
