# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-additional-scrape-configs
    namespace: monitoring
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    additionalScrapeConfigs: ENC[AES256_GCM,data:X6asLCmu2BUt1fklK5gJUsHMNeMC9IX8JhWaRrA9UAI6wcyAClAtWiXD38r7dDz1gr6WROiw95rA/Airgu0825DQGzmgQiu5HiceLtX62N9Icav7v6WjRZrjBU5/1DVjkFokvnHOkvHPMhcJF8gABHWnKx1uVAOs6MpTKAFwHRvErTAZ9EjSKvSuyZrK3Vs/QyxEi8c8/k6jwDLar3YG/BIyYohSTSyCOC7wKQ2CnEdT6V8lf9ua1nBdgN26NNc46F8cgRtJpxeaKQ2ss6mH1tuZS12sB+Y8E9uxbJ5/KM38X0/mUBaBnAAUm0bE5Hug5ItOr3q4SShLWhGSR170yEbYL8b6DDqSu4EGHH0yc0xCTW+nFMuXPj6uoXFpcFTgGiNMenpB2QFYA7BL41ZTWX1Zlp7DgVEtvlGkvoR6aMzANh+JaicuPA/UXggA3hjHu0HWPIsI/KZq2ksbp0RFdkhzScc87xXaCnz/l2Mby6AIpqYu//Lpokf9qV2yvQD72MzWqUXsG9fe01rGl9IzK9yDP7TZ/5LyzsTGL87xCFcFEXhfeDP6YkPNONfmWrurFAk7J6AFuaGgVUDRloF39ajZnj3RoJebN8Uqt/itWwf+CO9PXg6Da3sqaZk1Ioml5+fhv/w9ny0xM8M8oNso7j4oAcAgZNbtXvItu9OsxARL9iXXBgPDB+vfxHEHZAtze5Gyyqe/4VsaBnzxtlX8LJli4GunqshyUUdPT/sNqghLJt2fAlk45+E1cfZNXOS/Q1/MewU4wUHzgXSpat+XPXzOEWIwBpD5hL95Ri0TCdv7DF2ctPwZakQv97NFNjlJEdYBlpoJKvHCLbb8mFaA6Ua6Rx5anSyHat8e0YPk2XFmeZhTQvIEsaboiDp1NJrpeoeTe/luTOtQyNtwwMzXeR6XIfCE6mh8W4X1xm5sOo2C+jcEyiPk4msRRyXktJdbQz9Lev14Nzc//GvSu+MXJs1K78UZZ1v2MPRqsT10P7G/jnK67k4nJTnVgrZwCqKBR0A0oeTL91A4F+NfVDBpqHq7uxrrxOgf9XxMOxUzhzg2RnSyYXbKsjb3VfpYGZ0Jb7LzOuV0NnZXNQavGBf9OdEDsQxwMZ8APuDVOSLfKf69OMotUT/X5OF6O/LoO+HxGS96qzyExyCoEJDlaZHoJmz0rwIEV9bK7CyEp7rUNPzFPA==,iv:anpmayHG6cI8i1Mnkha34B6/IZcZRItm9Xvouw8XNEk=,tag:Ms9BuXPTf/Cab3X0Ix5r3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUHIzRDdOdm5sejB5RHpO
            T1A5dm5CZVJVenJDaXFrRkY2aDVQbUl3SXhzClVHSTlEMnRjc3ZyWXRJdWJza0sw
            VUNGbmtDK0ZCZjFjVUt0a0pXV01DQ3cKLS0tIGptbnFKWWE0Vnp1QnNxTnpmYi9W
            UjRhbXNsQVRZY01FdzJuSDd1TjA5b1EKv55bokwA9PinT31ichl5l/cSL8b8C3MR
            RdSSmBzgI08DgVaencF2NBdRIIS1wvxAGLNO1+jzgWYs1tuuUqiB1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:56:00Z"
    mac: ENC[AES256_GCM,data:RR3vbuLQ1bi/7d5H9vff/Ztcug81iqyMeNI2j9nYRLx2QoMxMFqNbE3Zux1TF/34kjUcHqtOlnEZiTawBoGZwMgowC9TLtnCatyJBZce1w8247vNeOkEdMtwF+ieu3ALxrakTF87R1J7tUMeNs6FO/XmzaTtmxncIMfsdGkGIUY=,iv:cMgSG158Jf3JlHwx0DO1DqNpFk6/nKy//lV9Z5SVe4Q=,tag:id7x7N3DhnJYGsS+COsiBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
