---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: dev
spec:
  releaseName: *app
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
      tag: 1.25.1@sha256:ea7901a9629897801b38b6afbce1869d357ebb9e080ec6ffff5839d85d8a79e4
    env:
      DATA_FOLDER: "config"
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_PORT: 3012
      DOMAIN: https://vault.${SECRET_DOMAIN}
      ADMIN_TOKEN: ${SECRET_VAULTWARDEN_ADMIN_TOKEN}
      # SMTP_HOST: ${SECRET_SES_SMTP_HOST}
      # SMTP_FROM: "${SECRET_SES_SMTP_FROM_EMAIL}"
      # SMTP_FROM_NAME: "VaultWarden"
      # SMTP_SSL: true
      # SMTP_PORT: ${SECRET_SES_SMTP_PORT}
      # SMTP_USERNAME: "${SECRET_SES_ACCESS_KEY}"
      # SMTP_PASSWORD: "${SECRET_SES_SECRET_KEY}"
    service:
      main:
        ports:
          http:
            port: &port 80
          websocket:
            enabled: true
            port: &websocket-port 3012
    ingress:
      main:
        enabled: true
      ingressClassName: "traefik-internal"
      host: vault.${SECRET_PUBLIC}
      path: /
      tlsSecret: ${SECRET_PUBLIC/./-}-tls
      tls: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        # traefik.ingress.kubernetes.io/router.middlewares: "auth-chain-authelia-auth@kubernetescrd"
        # external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_PUBLIC_DOMAIN}"
        # external-dns/is-public: "true"

    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
