# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    #ENC[AES256_GCM,data:k5gbOl6JKVAbz0KB/DBxnz2mV0hNrVLxfGrXJRmEClQoS28=,iv:1MrH9NCCKni0dW03cTr98cyIC/iq0bYCNyk4TfBIILA=,tag:EzRfDP89PA3KubzMXiWA+w==,type:comment]
    ENROLL_KEY: ""
    BOUNCER_KEY_traefik: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT1pSMEc4bWZHOGMrTjRR
            U3RtN2Zucjlqam5oeXNIQ0tMdDJMVkVxMW5nCi9mOU1WQWpDeGpZN1JmbnpsNjdC
            MVFkUGhtWlFsZHFIbkpPRG4vVXZpcG8KLS0tIHFLemFSWllHakowb0c4K3Q3bWFN
            MFFiMGNzS0F3NzZ6TnkwOThscVR6bGsKAVkNr38qu17bcW4HrJMB2wTfZiddpTsv
            QYAim7qbPWlnnjVX/kZ3DuUKAcgi2rai7CvmeVfQ9T7D6k2/vF5XAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:12Z"
    mac: ENC[AES256_GCM,data:ixoF5BlU+ceV1aOc3MKCFmbAWUfWZiORRBuSzy+bhJ2c0Hc+dj/lRIc2eqAXhTFeW8J3AHfTirjeipYrmCCKQW1RhEDraB02DeW1uCTtqPRtrY/2rH07JsyeDYFMNxG3ZrVM5Dd5AkZx8YFZ49D6tCOsknJVEEWcKHepiSkqoNQ=,iv:iUQUsiFFDj7JWeyAKtNOx5pQNyq0s+9N2Bc8hFA9Q/I=,tag:HdEZp8w2aWoihGZORTCvnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
