---
# yamllint disable
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
  annotations:
    reloader.stakater.com/match: "true"
data:
  TIMEZONE: Asia/Kuala_Lumpur
  NET_NODE_CIDR: 10.2.118.0/24
  NET_POD_CIDR: 10.42.0.0/16
  NET_SVC_CIDR: 10.43.0.0/16
  LB_GATEWAY: 10.32.1.212
  LB_INGRESS: 10.32.1.213
  LB_AUTH: 10.32.1.214
  LB_DEFAULT_RANGE: 10.32.1.230-10.32.1.250
