---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: esphome/esphome
      tag: 2023.3.2

    service:
      main:
        ports:
          http:
            port: 6052

    hostNetwork: true

    ingress:
      main:
        enabled: false

    persistence:
      esphome-cache:
        enabled: true
        type: emptyDir
        mountPath: /config/.esphome
      config:
        enabled: true
        existingClaim: "esphome-config"

    resources:
      requests:
        cpu: 300m
        memory: 512M
      limits:
        memory: 2048M
