# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: homebox
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    HBOX_MODE: ENC[AES256_GCM,data:hx231tTC+YJHDg==,iv:LdnAdf1nCMCHC3Z90o0PfdDpWdbj19rOinxT1IOJJac=,tag:SaV/G/N3YYeT9pwJlG71dQ==,type:str]
    HBOX_OPTIONS_ALLOW_REGISTRATION: ENC[AES256_GCM,data:fpDCrg==,iv:KsiZv5ASV6bMCk77P7aEIqKnDOBHCaZlMKPN2Il13Zw=,tag:RSxKO85wqsuGue9Y/ry6LA==,type:str]
    #ENC[AES256_GCM,data:OLXErV9nqS6BHtqbUy2Ykto=,iv:+iFqhBPNPRgUbTbkZBobvvzNuLqL+GyPUlazWF4duk0=,tag:xANepc1N/unhzJ3niZifIg==,type:comment]
    HBOX_MAILER_HOST: ""
    HBOX_MAILER_PORT: ""
    HBOX_MAILER_USERNAME: ""
    HBOX_MAILER_PASSWORD: ""
    #ENC[AES256_GCM,data:J1lTjgfABTuSJN5n6CMxADJlHOLE6zjbpNs=,iv:lfEbw7YgTS9S61f4wbJFTffHc4gWIAPlAxKigg+KccM=,tag:4rEQSlvly5XMfzvVkEV/Tg==,type:comment]
    #ENC[AES256_GCM,data:hJ49aQknjrlnDoB0AZzJ0yrKXS3GQ+ZlkH4=,iv:pYNPApuGh0gLxuZH5ogim//THZzXYkS6OEz/Myxk9rA=,tag:AV9SVSDoudHRhgzHkMkDiQ==,type:comment]
    HBOX_MAILER_FROM: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWndmTThzbDNkZGRJV1k5
            aHlLSnFpN21WcHUyQTQxTFJBR0JkOVNyMGhBCmQzNE5LVFAzT2c5V2EyQ2p0TFow
            b3NraHlscmg0K3NIS3phRjRMdGEyRVEKLS0tIFE4UG1CN1FOSDJ6TUtkcm0vTFJz
            amhEaklLMzRNYldtcDNlWHIzQzdqalEK4Er4lRF7h0gdHhn8COFY1Hz66x/tinZN
            A4CbGk4r9rpslQED9RlWD/0B3Cmohoqc1DY5lmVrhwy/lqdI3Ob5xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:55:59Z"
    mac: ENC[AES256_GCM,data:miAVRwjOA7vD7RaBJQQtPFHxVNe6frlfQ3BHdRCzGQpXM9MDSaO0jL8f2WQGylZTWY40UJuGc3Dpa71kcoGgMGvs7qzReGuaSn4MJZQcEkHzAlcMx5fdD5CPlZAEbEZSldvRoHnojVCKnOpyQmSgyP4zlwY/NSzWoYW+QRRSwfU=,iv:5PyCfk5bum9E+Z+p4nHOuI8JU+RlS44r/lo3GEFmQfE=,tag:dxspJTmlKiuWjEma0UGWuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
