---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: dev
spec:
  releaseName: gitlab
  chart:
    repository: https://charts.gitlab.io/
    name: gitlab-omnibus
    version: 14.4.1
  values:
    global:
      ingress:
        configureCertmanager: false
      hosts:
        domain: ${SECRET_DOMAIN}
    gitlab:
      certmanager:
        install: false
      ingress:
        annotations:
          traefik.ingress.kubernetes.io/redirect-entry-point: websecure
        tls:
          enabled: true
          secretName: ${SECRET_DOMAIN/./-}-tls
        hosts:
          domain: gitlab.${SECRET_DOMAIN}
          tls: true
      initialRootPassword: changeme
      omnibusConfig:
        gitlab_rails:
          gitlab_email_enabled: true
          gitlab_email_from: gitlab@${SECRET_DOMAIN}
          smtp_enable: false
          # smtp_address: smtp.gmail.com
          # smtp_port: "587"
          # smtp_user_name: gitlab@${SECRET_DOMAIN}
          # smtp_password: ${{GITLAB_SMTP_PASSWORD}}
          # smtp_authentication: plain
          # smtp_domain: smtp.gmail.com
          # smtp_enable_starttls_auto: true
