# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    #ENC[AES256_GCM,data:isBuiA3uzdrtZp+vqyefGlbTLkzIandO0yATd2Fgif4f+w==,iv:+kRGKFdzEKGZZGjoz3RYizHz42A49RRWBEudm7gHbPg=,tag:ekWr+ztfcddIducjuLCPdw==,type:comment]
    password: ENC[AES256_GCM,data:Uf7vUTtB0xXMqiQO+KS5kRWxUJqs39XNB9dSnqNIcryHjkMp5Uw5L0S9AxVm9g==,iv:pVuAguBGk4c2IVLgThss9vCSyMJGNuKFA51WwCkSplk=,tag:ZAdPqc6cRlAjTLwcU0Czyw==,type:str]
    servers.json: ENC[AES256_GCM,data:4aWc2VQngYZQbxXK2GhWfUOGohAYYVEHjCpEp22oUvvUz11QH6haVG11HKOzCVSgNI5jf7RSFnro9jNlVZwy4k8vvPsFCnON2gh7Gs3Z+gvnmPrlwKMVnpk66wZs3umOOWq4vf+LD4fI0y8dRyXAkevO595jaH34ScTTXI/3rQl6hbcAzgF2sACZtM44rnEv+MAlVDGusjYKyyBXnb9uoc16pBchLt0DZYPSDM6M7XovdbRP5v3Ed8Rg2evjJGBxHxDkSUnPiXiBi7FA52o35c+77qXwHDDPQwgE8bw9X7rJXEs2lpZD7sAM9CQ/rHiJLtSraOwa7oQahdhkwZ+5M4FHdxF1LW4=,iv:D4/+/qIaiagMYD7sme569mHzf3QvNkKLDpN94gWDP3U=,tag:3gcOqrTO+4+suAMGZq+mBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa2N4UlF3MGZFdXVDM1o0
            RnBHUVd0WUhMdGpEeDU3Ni8zM3F3eFVBd0VnCnVETkRvQ3pZSHlOenBpSFBVZ2pj
            Nm4vdWwzQ2R6QjBEaWVMZG5OMjdWRG8KLS0tIE1CSzgzNmcrV1RmM1ZzSHBDZXhQ
            RjdXRHl3dnM2cGdRcndIekc1dDRwTUkK0c60hXgxZw7NCxfSs2FHacPvXQbU/NKN
            E1lrH0c6nLps2SqJgPC7ALVUke5JhQtXI2Ipjvbcy0V3tNmanNYKGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:55:59Z"
    mac: ENC[AES256_GCM,data:0TdPusYkBXVkfEiHuBN5OjhzptBx71GOa+6pZTS7dO7OAZOjyXFQsUPthtvw/1W+Zccsv9TDZrAjUAXIh3adykfMI6k1XvbauaVGVZzAtE6LovWlVk7wSk/hyhU6PNjeAsI3BZ4gJUNrkgvoed2x9l1dkW+J3lHwpm8VWHCgB5Y=,iv:e0+ef0t1QBTZ774AJMJwkjPIyvYwi8l4qYaxRufDFV0=,tag:0bRjSvYAzd779cFwx9WyvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
