# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    #ENC[AES256_GCM,data:ADTb89nyqxEDZ/B0H5SJJMODiyngacr3TR1C69S8wcaUNA==,iv:KcNscWnRCCXhl0eFI6PirisXqV2hty4xy5p31e34YPc=,tag:EyFpLgSoW/ezIJWnMMH+bw==,type:comment]
    password: ENC[AES256_GCM,data:B6KkgoIQ6Rg852od0QUP1klei5Y9tHIi+fED,iv:mx21G1KyHKQCAbeLkJiUIT1RiNYArWaOcaxjXjlUnLg=,tag:elYHVr2jCIVOAufJaWColA==,type:str]
    servers.json: ENC[AES256_GCM,data:beMdChR/R/3UdY0g3ojnsnz/pVbGw7gylkP4ldKZtZa13F7Mf9wnVV2zp83/6vXoJnnqM1t21ZPejFdoisGYpnw3DcnqvKENwSuATsuCzag8rgkRyVDweIa9YZwe0+abUE/eCmp3E3xe5CmcDSEiwwIXpmUt48im2s49PVpGXUWa7PE4/5c64I5hipTE0QERvWbvsd9l/uQ37PAXhOrTtYXASKErMgFEsY0tf0yT09tCXiifH9wzZh+f9MqXnQaitbCC4A8YyuZwXkAmvwTJhsWCZ66ml6kDe1PECgWxJpXOnGA7MRvvFKG4OoZmngcEWVfd7CcFKuetFsnFHCDQBwEk2dLasw==,iv:E2SuqMX57TdKvgEh3FJxz0tu6se9X5IQBLr0RIJ+zps=,tag:98RMAtA+CD5IkLxf9vCn8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLLzNNNktIeUVDTXIzMFA2
            aEhDUU9jNS9DL0pPbUlSUmZxb3ZEbGVDVHdnCk1pZmVTZk9Zcnlzc2VBTUF1ajdV
            RW5BTmFRQW0rcmlEd2tUanIzRnp6UkUKLS0tIFhnMDkrVE15WXdvcStvdUdGMUFp
            WkpmR3cvanJlT1NJaXg0MGsza1FBRnMKCqU6aw8KUwbPE2/V692kaxdclB6dLxw/
            xhoY0m1Wglb03AUclIcLASjuArZOr1Rg+xmkXKGdqOaJsWM00lSFcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-30T01:02:18Z"
    mac: ENC[AES256_GCM,data:4MnrDRZ5XZb+XDADXnkm14etK/vwj1RJMDypoI0QKiY8PyTWedBsGs1z5rFaFCl31MM2MIqjg7qTfs8x//uqI/67XaYoCa+RhWcNzCJguMUMAwEW7LvA9HHiHX/orDgOv7jym16lY0T+8iLgwsq73YaiiTazsArzOjh2kmci+Fo=,iv:HTUrEKMvpOGy6C/cyLZMAKVba8IHWYzNpbGFa5ltSJI=,tag:O9P3xNNlH1S94i4iDQcenw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
