# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser-secret
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    username: ENC[AES256_GCM,data:F/U4mqpHUrU=,iv:nRXgML+FPv8MmRD2RVFUMjMrWFAexid5jgEh5ZHG4po=,tag:ud4Lhx6o6kmpwPKuKoIDvQ==,type:str]
    password: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN05URWlxNXVCdWxtQUR1
            Q1BPbVhEMEs5cVVWbmVQMjdCejZMQUVRTmpJCmZUem96NHlERjdsdEhnWW54ZlAv
            cTFOUWU1dTN1V3lURFp6bnRWdklNWHMKLS0tIDNuYVcwS1FKSW9LVE5pWnRNTXFt
            MjJITmI3VVdDUXBGaGRrVUNqSE1VVG8KQVCzlIsK9YPEpRTnRh8/cO4E5JHu8Zsc
            96mZExI084OeftztsmUq/QRlQfQMbIcEsnDifHaM60EvUMmou1NyDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:1/pDGJkLwM4KUQn3G0kBVLNW6nwX4pLtHQVgN/itQEYq5xPBnv5C3uX0idGfYlrI+azSGeamA5sX4ojoMm+BVq0yo0+t1IKbAKezXzEODJ6yg/CedkjDISEum43xMZzw70f7fiQjTfiO+/opxGtdya5YO0PrL8VAVoApZjJqKZk=,iv:+czWECSadcjMq4ddSUWOOaw4qRdDhzVsCNsvXkH8tI4=,tag:7UG5cHnc64HW3Ka0/R/rBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-s3-secret
    namespace: default
type: Opaque
stringData:
    S3_ACCESS_KEY: null
    S3_SECRET_KEY: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN05URWlxNXVCdWxtQUR1
            Q1BPbVhEMEs5cVVWbmVQMjdCejZMQUVRTmpJCmZUem96NHlERjdsdEhnWW54ZlAv
            cTFOUWU1dTN1V3lURFp6bnRWdklNWHMKLS0tIDNuYVcwS1FKSW9LVE5pWnRNTXFt
            MjJITmI3VVdDUXBGaGRrVUNqSE1VVG8KQVCzlIsK9YPEpRTnRh8/cO4E5JHu8Zsc
            96mZExI084OeftztsmUq/QRlQfQMbIcEsnDifHaM60EvUMmou1NyDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T16:53:11Z"
    mac: ENC[AES256_GCM,data:1/pDGJkLwM4KUQn3G0kBVLNW6nwX4pLtHQVgN/itQEYq5xPBnv5C3uX0idGfYlrI+azSGeamA5sX4ojoMm+BVq0yo0+t1IKbAKezXzEODJ6yg/CedkjDISEum43xMZzw70f7fiQjTfiO+/opxGtdya5YO0PrL8VAVoApZjJqKZk=,iv:+czWECSadcjMq4ddSUWOOaw4qRdDhzVsCNsvXkH8tI4=,tag:7UG5cHnc64HW3Ka0/R/rBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
