# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser-secret
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    username: ENC[AES256_GCM,data:lcBWgLsFza8=,iv:IZOt5AwF9KAPRw9hyayWgsdL4uV05lqvJp6S8DXm5YA=,tag:1vEh5Iwm3TD2HL25maEiVg==,type:str]
    password: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSGRseXAvd2dicENLRU94
            dWF4TG5TaVppK0NiNENPZGtxeVJnUVNEaEgwCmhMMXM1S2FzMjJVN2xRUmt2MnRO
            YjhENTFEUGZvcnRpM0pPUityRUtWbVkKLS0tIEp3YytuTU9XdjIzcmpvbWdzYXRw
            VzRsdGdoalFiRnVidXdwM3EvY2ljLzgKwIlFjlnsV6M/4lRBNvwWxdli9cTxPfFC
            HoI/lisSiuD6CmV3ghUSsniDsw7E+hGohYwxohdegi7zirAGDPtp7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:55:59Z"
    mac: ENC[AES256_GCM,data:D7YDwb9jGyf8fy4JmbiIVSseJ0mlBn/AxlVg7de0DN4zOsTrmJuhopveTzl4tJFdd32af32DYBj4UcC3mZUOtBT0drJIPP2ilbBmUH/3H0PILyKa3CzxS6re1xiby1j80i4x/+Hz7lOBcZ5M630Ivfm92HUqID2pDZI5M3vBwo4=,iv:eBGXOJfjhRtkDBDJg0F1UoVCpjLUR+oVqo+vsHJGT28=,tag:lL1oBF4a7NASwwXW9asMmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-s3-secret
    namespace: default
type: Opaque
stringData:
    S3_ACCESS_KEY: null
    S3_SECRET_KEY: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSGRseXAvd2dicENLRU94
            dWF4TG5TaVppK0NiNENPZGtxeVJnUVNEaEgwCmhMMXM1S2FzMjJVN2xRUmt2MnRO
            YjhENTFEUGZvcnRpM0pPUityRUtWbVkKLS0tIEp3YytuTU9XdjIzcmpvbWdzYXRw
            VzRsdGdoalFiRnVidXdwM3EvY2ljLzgKwIlFjlnsV6M/4lRBNvwWxdli9cTxPfFC
            HoI/lisSiuD6CmV3ghUSsniDsw7E+hGohYwxohdegi7zirAGDPtp7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T15:55:59Z"
    mac: ENC[AES256_GCM,data:D7YDwb9jGyf8fy4JmbiIVSseJ0mlBn/AxlVg7de0DN4zOsTrmJuhopveTzl4tJFdd32af32DYBj4UcC3mZUOtBT0drJIPP2ilbBmUH/3H0PILyKa3CzxS6re1xiby1j80i4x/+Hz7lOBcZ5M630Ivfm92HUqID2pDZI5M3vBwo4=,iv:eBGXOJfjhRtkDBDJg0F1UoVCpjLUR+oVqo+vsHJGT28=,tag:lL1oBF4a7NASwwXW9asMmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
