# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser-secret
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    username: ENC[AES256_GCM,data:F/U4mqpHUrU=,iv:nRXgML+FPv8MmRD2RVFUMjMrWFAexid5jgEh5ZHG4po=,tag:ud4Lhx6o6kmpwPKuKoIDvQ==,type:str]
    password: ENC[AES256_GCM,data:SElwydO/JkKh,iv:Kk0AhcSTx4+6lb+a+HSiGxfvrkX1AslHrpBjNe5ivFk=,tag:x4tny0VsnBY8eYURgt0isw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN05URWlxNXVCdWxtQUR1
            Q1BPbVhEMEs5cVVWbmVQMjdCejZMQUVRTmpJCmZUem96NHlERjdsdEhnWW54ZlAv
            cTFOUWU1dTN1V3lURFp6bnRWdklNWHMKLS0tIDNuYVcwS1FKSW9LVE5pWnRNTXFt
            MjJITmI3VVdDUXBGaGRrVUNqSE1VVG8KQVCzlIsK9YPEpRTnRh8/cO4E5JHu8Zsc
            96mZExI084OeftztsmUq/QRlQfQMbIcEsnDifHaM60EvUMmou1NyDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T05:48:38Z"
    mac: ENC[AES256_GCM,data:Gz1cd7tBgq9QYPUQhvkUx3V8ryLCjMQ5stheOYQrlWgzuHU/bkQAOu8v+XRICvENZOpCnacnFqpnBBAoF/N12BujfliyP+TJsG9Imm+k7YrkUDIjj2tddWg7ZK0Md1cDeh3jR+3VzqzygESqMScooK1nAb225iCeWTpSzlYjVIE=,iv:MjoWSwBnJ8tYT1nY/aoDaqOZW4htUJWbrWibjjzTW5U=,tag:hESlvuRrEJRjXfLJDGNC1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-s3-secret
    namespace: default
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:Ue5Z7N7a4pugTAIljDngAcqX+pg=,iv:OMmcPZ8up86zs2l2KvjqHT0dNTC6zHc1klK9el8gqDw=,tag:qilXWbAFfUICvtKiaKRtOQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:Ip1/vZ4HK3VVx6A+dGeMNkO9nNLim2Ye24JGXk5n+pBztsWwvGI5JQ==,iv:IscAKz1mVIkmOTxaikUXCOSlPGv8VRG60rrqzHzs0g8=,tag:hF4TPe13iWDib2UyMuI5sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN05URWlxNXVCdWxtQUR1
            Q1BPbVhEMEs5cVVWbmVQMjdCejZMQUVRTmpJCmZUem96NHlERjdsdEhnWW54ZlAv
            cTFOUWU1dTN1V3lURFp6bnRWdklNWHMKLS0tIDNuYVcwS1FKSW9LVE5pWnRNTXFt
            MjJITmI3VVdDUXBGaGRrVUNqSE1VVG8KQVCzlIsK9YPEpRTnRh8/cO4E5JHu8Zsc
            96mZExI084OeftztsmUq/QRlQfQMbIcEsnDifHaM60EvUMmou1NyDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T05:48:38Z"
    mac: ENC[AES256_GCM,data:Gz1cd7tBgq9QYPUQhvkUx3V8ryLCjMQ5stheOYQrlWgzuHU/bkQAOu8v+XRICvENZOpCnacnFqpnBBAoF/N12BujfliyP+TJsG9Imm+k7YrkUDIjj2tddWg7ZK0Md1cDeh3jR+3VzqzygESqMScooK1nAb225iCeWTpSzlYjVIE=,iv:MjoWSwBnJ8tYT1nY/aoDaqOZW4htUJWbrWibjjzTW5U=,tag:hESlvuRrEJRjXfLJDGNC1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
