# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser-secret
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    username: ENC[AES256_GCM,data:F/U4mqpHUrU=,iv:nRXgML+FPv8MmRD2RVFUMjMrWFAexid5jgEh5ZHG4po=,tag:ud4Lhx6o6kmpwPKuKoIDvQ==,type:str]
    password: ENC[AES256_GCM,data:mKPYmDIF/+zXEqT8ejzepsMdbtSFyi+6UeI=,iv:XFbZjme6/dJx+v0daJhuwmyq66U0Ll/Lo9ZtMkiuZu8=,tag:+v997zhfJbME6fYPJgVDjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN05URWlxNXVCdWxtQUR1
            Q1BPbVhEMEs5cVVWbmVQMjdCejZMQUVRTmpJCmZUem96NHlERjdsdEhnWW54ZlAv
            cTFOUWU1dTN1V3lURFp6bnRWdklNWHMKLS0tIDNuYVcwS1FKSW9LVE5pWnRNTXFt
            MjJITmI3VVdDUXBGaGRrVUNqSE1VVG8KQVCzlIsK9YPEpRTnRh8/cO4E5JHu8Zsc
            96mZExI084OeftztsmUq/QRlQfQMbIcEsnDifHaM60EvUMmou1NyDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T19:46:31Z"
    mac: ENC[AES256_GCM,data:LVWa9nh6GtQJQdTmNoS8rUqTeVqUGsL61b9iXgauVnfYN63LNt9SmxPuzm2vYsCMsvz48Q71yjyyJ2nKhULMmwjp3GVB9yi4cUStfSkcINhiyXULRBxVf7at1cdLkIuMJnr3m9YIZhXrTj6da6mlTIjCP4PMCqiwD+z0j9fJYnA=,iv:MZgNqi6DSwoSF+4ZBBDA3j7NCTY8n8JOYKN9hUjCxSM=,tag:S+ltjHzxuzxX407NW8/wyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-s3-secret
    namespace: default
type: Opaque
stringData:
    S3_ACCESS_KEY: null
    S3_SECRET_KEY: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1atndjnkcvdzk46u5s7gfdetxlkwg966nelqz62xj3klemdh83uasq82hgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN05URWlxNXVCdWxtQUR1
            Q1BPbVhEMEs5cVVWbmVQMjdCejZMQUVRTmpJCmZUem96NHlERjdsdEhnWW54ZlAv
            cTFOUWU1dTN1V3lURFp6bnRWdklNWHMKLS0tIDNuYVcwS1FKSW9LVE5pWnRNTXFt
            MjJITmI3VVdDUXBGaGRrVUNqSE1VVG8KQVCzlIsK9YPEpRTnRh8/cO4E5JHu8Zsc
            96mZExI084OeftztsmUq/QRlQfQMbIcEsnDifHaM60EvUMmou1NyDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T19:46:31Z"
    mac: ENC[AES256_GCM,data:LVWa9nh6GtQJQdTmNoS8rUqTeVqUGsL61b9iXgauVnfYN63LNt9SmxPuzm2vYsCMsvz48Q71yjyyJ2nKhULMmwjp3GVB9yi4cUStfSkcINhiyXULRBxVf7at1cdLkIuMJnr3m9YIZhXrTj6da6mlTIjCP4PMCqiwD+z0j9fJYnA=,iv:MZgNqi6DSwoSF+4ZBBDA3j7NCTY8n8JOYKN9hUjCxSM=,tag:S+ltjHzxuzxX407NW8/wyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
