---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-dev-vaultwarden
  namespace: flux-system
spec:
  path: ./kubernetes/apps/dev/vaultwarden/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-gitops-k3s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vaultwarden
      namespace: dev
  interval: 30m
  retryInterval: 1m
  timeout: 3m
